# 無効にするルール
disabled_rules:
# 余分に改行がある方が視認性が上がる為、無効
- trailing_whitespace
# クラス名は長くして情報を詰めておく必要もある為、無効
- type_name
# 不正なキャストに対する警告は、とりあえず無効にしない
# - force_cast
# TODOコメントによるwarningを抑止
# - todo

# 一行の文字列制限
line_length: 300

# Lint対象から外すファイルのあるパスを記述
excluded:
- Pods
- Carthage
- PTPIPProtoTests
- PTPIPProtoUITests

# クラスの行数
type_body_length:
- 200 # warning
- 400 # error

# 関数の長さ
function_body_length:
- 100 # warning
- 200 # error

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  allowed_symbols:
    - _
  excluded: # excluded via string array
    - id
    - ok
    - ng
    - awb
    - URL
    - GlobalAPIKey
    - ps
    - pa
    - l
    - s
    - m
    - m6
    - m4
    - mf
    - pf
    - on
    - up
    - f2
    - f4
    - f5
    - f8
    - f9
    - x
    - y
    - z
# タプルの値の数の上限
large_tuple:
- 5  # warning
- 6 # error

